# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b2ce72e186db8b05799bfc795c03d6748d15135f6738d2a71f52d3d1ac38b0c7d89477efe593b82536015a677fb2f82e809b35f8f58357c422cbf74fcff63d

test:
  secret_key_base: 34640ab93d4443a26b9c4a6d95c08cd52345bc41215a053f514714bb263680f7caaf271f7364798b4b922763b91a114d1451db73375d7bc864c203a9163a7d4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
